# Generated by Django 3.1.7 on 2022-04-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
    ]
